### ISSUE TITLE
models are not being retrieved for some users

### ISSUE THREAD

**Issue by Reda-S** [LanceMcCarthy/RemixDownloader#12]
The app is working fine for Microsoft or xbox's user ID but not for other users, example:
3nL7Bg5W5-c, 3njdeeiH3Bm, 3wGpgNg-Ayc ...

**Comment by LanceMcCarthy** [comment]
Hi Reda,

I've been trying to replicate this, but have not been able to see the same issue. I have two ideas on what the problem might be:

1. The IDs are case sensitive

Make sure that the text is exactly what you see in the URL

2. Empty or hidden characters

It is also possible that the paste had some extra spaces after it. I will add automatic trimming to prevent any trailing empty spaces from messing this up https://github.com/LanceMcCarthy/RemixDownloader/issues/15

In the latest update, I have the app load the user first so you can see the user's name and profile picture, so this should help prevent some problems.
