### ISSUE TITLE
Cannot open GLTF file in any 3D viewer.

### ISSUE THREAD

**Issue by byterace** [LanceMcCarthy/RemixDownloader#19]
I cannot view any of the GLTF files that the console application downloads.
I chose the default user ID and had it only download the original model file, however 3D viewer will not open it and 3D builder says it needs me to browse for the Binary data file.
![image](https://user-images.githubusercontent.com/4693205/62839971-c4aeca00-bc47-11e9-80a8-e0385378d9e2.png)

**Comment by parrotmac** [comment]
This should be fixed in #20

**Comment by LanceMcCarthy** [comment]
Sorry for the delay, folks. I just merged the PR. I'll try some further tests with Blender and Print3D to see if I can replicate this again.

**Comment by LanceMcCarthy** [comment]
Thanks to @parrotmac jumping in to help, the additional assets and bin files are downloaded with the GLTF. 

![image](https://user-images.githubusercontent.com/3520532/63551164-61078500-c502-11e9-8de7-eca7ba3e4545.png)

Once the DevOps pipelines are done building and packaging v1.0.1, it will add a release to the releases tab.

**Comment by LanceMcCarthy** [comment]
@byterace There's a new release available that has these fixes https://github.com/LanceMcCarthy/RemixDownloader/releases/tag/Release-7

 Thank you for your patience and big thanks to @parrotmac for opening the PR so I can merge his work into the project.
