### ISSUE TITLE
Save to User-Selected Folder instead of LocalFolder

### ISSUE THREAD

**Issue by LanceMcCarthy** [LanceMcCarthy/RemixDownloader#4]
Currently, for quick development reasons, the models are saved to the LocalFolder of the application. This would be difficult for a non-savvy user to locate.

Instead, let the user select a location using FilePicker and save the models there instead.

**Comment by xiaoliwe** [comment]
yes,that's very important for consumers.
but, even if the download path is found and then how to get 3D model files ?

**Comment by LanceMcCarthy** [comment]
@winecos the next push to this repo will contain a way to set the preferred download location.

Until then, you would open the LocalFolder location of where the app is installed. The files are downloaded directly there.

Here's a screenshot to help guide you:

![image](https://user-images.githubusercontent.com/3520532/61312674-e8a4fa00-a7c6-11e9-9ee4-2c73884a3227.png)

**Comment by LanceMcCarthy** [comment]
Added this in the latest update:

![image](https://user-images.githubusercontent.com/3520532/61333383-bdd19a80-a7f4-11e9-89e9-5b0b7faf01c1.png)
