### ISSUE TITLE
preview failing

### ISSUE THREAD

**Issue by Reda-S** [LanceMcCarthy/RemixDownloader#9]
I am not able to download the preview image: when selecting "preview" as the level of detail and clicking "start download" it is always "failed"

**Comment by LanceMcCarthy** [comment]
Thanks for the report, I'm looking into this now. 

From what I can tell on the site's API, is that Preview is a very low poly version of the model and is used for the in-browser glTF viewer.

**Comment by Reda-S** [comment]
Oh I thought it was the preview image of the model... In any case, thanks for this downloader, it is great!

**Comment by LanceMcCarthy** [comment]
I know there is nothing in the way of documentation at this point, I'll probably add some `TeachingTips` to the UI in the next update. I did just update the README with some more information to make this easier to get started.

The preview image of the model is actually what you're seeing in the list. I know sometimes they get cut off and you can't see the whole thing, I'll be able to get to UI polishing after I get the core functionality working.

That being said, it should have not failed when selecting the preview option. I'll be able to take a closer look tomorrow and push a fix.

**Comment by LanceMcCarthy** [comment]
All fixed. Get the latest from `master`. I also made this significantly easier to use. It will download the original model file by default, 

However, if you some extra optimized ones (i.e. Preview, Performance, HoloLens or Mixed Reality), tick their checkbox. If the model has it, it will download and save next to the original:

![image](https://user-images.githubusercontent.com/3520532/61584420-59c11600-ab15-11e9-9f1e-9ccb36767443.png)
